name: Cinexis Remote FRPC
version: "0.2.19"
slug: cinexis_remote
description: >-
  Cinexis Remote Access: securely expose Home Assistant UI using Cinexis Cloud (FRP).
  No Home Assistant YAML changes required.
url: https://github.com/cinexisin/ha-p2p-v2
arch:
  - amd64
  - aarch64
  - armv7
startup: services
boot: auto
init: false
host_network: false
ingress: false
panel_icon: mdi:cloud-lock

options:
  frps_host: "cinexis.cloud"
  frps_port: 7000
  pair_api: "https://pair.cinexis.cloud"
  ha_scheme: "http"
  ha_host: "homeassistant"
  ha_port: 8123
  frps_addr: "139.99.56.240"
  ha_subdomain_suffix: ".ha.cinexis.cloud"
  debug_print_secret: false

  auto_wait_for_license: true
  retry_seconds: 15
schema:
  frps_host: str
  frps_port: int
  pair_api: str
  ha_scheme: list(http|https)
  ha_host: str
  ha_port: int
  frps_addr: str
  ha_subdomain_suffix: str
  debug_print_secret: bool
  auto_wait_for_license: bool
  retry_seconds: int
