name: Cinexis Remote FRPC
version: "0.2.23"
slug: cinexis_remote
description: >-
  Cinexis Remote Access: securely expose Home Assistant UI using Cinexis Cloud (FRP).
  No Home Assistant YAML changes required.
url: https://github.com/cinexisin/ha-p2p-v2
arch:
  - amd64
  - aarch64
  - armv7
startup: services
boot: auto
init: false
ingress: false
panel_icon: mdi:cloud-lock

  auto_wait_for_license: true
  retry_seconds: 15

map:
  - share:rw
  - config:ro
