name: Cinexis Remote FRPC
version: "0.2.27"
slug: cinexis_remote
description: Secure remote access for Home Assistant via Cinexis Cloud.
arch: [amd64, aarch64, armv7]
startup: services
boot: auto
init: false
ingress: false
panel_icon: mdi:cloud-lock
options: {}
schema: {}
map:
  - share:rw
  - config:ro
