name: "Cinexis Remote"
version: "0.2.0"
slug: "cinexis_remote"
description: "Cinexis Remote Access: securely expose Home Assistant UI using Cinexis Cloud (FRP)"
arch:
  - amd64
  - aarch64
  - armv7

startup: services
boot: auto
init: false

host_network: true
ingress: false
panel_icon: "mdi:cloud-lock"

map:
  - config:rw
  - share:rw
  - ssl:rw

options:
  frps_host: "cinexis.cloud"
  frps_port: 7000
  token: "CHANGE_ME_STRONG_TOKEN"
  ha_scheme: "http"
  ha_host: "127.0.0.1"
  ha_port: 8123

schema:
  frps_host: str
  frps_port: int
  token: str
  ha_scheme: list(http|https)
  ha_host: str
  ha_port: int
