name: "Cinexis Remote FRPC"
version: "0.2.12"
slug: "cinexis_remote"
description: "Cinexis Remote Access: securely expose Home Assistant UI using Cinexis Cloud (FRP)"
arch:
  - amd64
  - aarch64
  - armv7

startup: services
boot: auto
init: false
host_network: false
ingress: false

panel_icon: "mdi:cloud-lock"

options:
  frps_host: "cinexis.cloud"
  frps_port: 7000
  pair_api: "https://pair.cinexis.cloud"
  pair_code: ""
  ha_scheme: "http"
  ha_host: "homeassistant"
  ha_port: 8123

schema:
  frps_host: str
  frps_port: int
  pair_api: str
  pair_code: str
  ha_scheme: list(http|https)
  ha_host: str
  ha_port: int
